Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 as a placeholder for Ubuntu 24

  # DevOps VM
  config.vm.define "devops_vm" do |devops|
    devops.vm.network "private_network", ip: "192.168.56.101"

    devops.vm.network "forwarded_port", guest: 8080, host: 8080 # Jenkins
    devops.vm.network "forwarded_port", guest: 9000, host: 9000 # SonarQube

    devops.vm.provider "virtualbox" do |vb|
      vb.name = "DevOps_VM"
      vb.memory = 51200
      vb.cpus = 8
    end
  end

  # Monitoring VM
  config.vm.define "monitoring_vm" do |monitoring|
    monitoring.vm.network "private_network", ip: "192.168.56.102"

    monitoring.vm.network "forwarded_port", guest: 9090, host: 9090 # Prometheus
    monitoring.vm.network "forwarded_port", guest: 9100, host: 9100 # Node Exporter
    monitoring.vm.network "forwarded_port", guest: 3000, host: 3000 # Grafana

    monitoring.vm.provider "virtualbox" do |vb|
      vb.name = "Monitoring_VM"
      vb.memory = 8192
      vb.cpus = 2
    end
  end
end