apiVersion: v1
kind: Service
metadata:
  name: todolist
  labels:
    app: todolist
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
  selector:
    app: todolist